# -*- coding: utf-8 -*-
# Copyright 2013 Savoir-faire Linux
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "SIGE INSTALL",
    "version": "11.0",
    "license": "AGPL-3",
    "author": "IP-TECH",
    "depends": ["backend_theme_v10",
                "base_config",
                "employee",
                "etablissement",
                "help_online",
                "hr_recrutement",
                "hr_absence",
                "hr_assignment",
                "hr_employee_documents",
                "hr_employee_id",
                "hr_evaluation",
                "hr_experience",
                "hr_family",
                "hr_formation",
                "hr_language",
                "hr_skill",
                "jasper_load",
                "jasper_reports",
                "odoo_debrand_vneuron",
                "odoo_web_login",
                "report_rtl",
                "report_xlsx",
                "reporting_sige",
                "scolarity",
                "stud_assignment",
                "student",
                "student_absence",
                "student_health",
                "student_inscription",
                "vneuron_restful_api",
                "vneuron_workflow_odoo",
                "web_advanced_search",
                "web_disable_export_delete_button",
                "web_responsive",
                "web_rtl",
                "website_rtl",

                ],
    'data': [],
    'installable': True,
}
